/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pinguinoconpulgares (https://sketchfab.com/pinguinoconpulgares)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/humanoid-robot-385ae553cfda40d1aaadd96d11a19949
Title: Humanoid robot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ color, ...props }) {
    const { nodes, materials } = useGLTF('/scene.gltf')

    // Clone materials when a color is requested to avoid mutating the original cached material
    const headMaterial = React.useMemo(() => {
        if (!color) return materials.HEAD; // Return original if no Custom color
        const cloned = materials.HEAD.clone();
        cloned.color.set(color);
        return cloned;
    }, [color, materials.HEAD]);

    const bodyMaterial = React.useMemo(() => {
        if (!color) return materials.BODY; // Return original if no Custom color
        const cloned = materials.BODY.clone();
        cloned.color.set(color);
        return cloned;
    }, [color, materials.BODY]);

    const extraMaterial1 = React.useMemo(() => {
        if (!color) return materials.material;
        const cloned = materials.material.clone();
        cloned.color.set(color);
        return cloned;
    }, [color, materials.material]);

    const extraMaterial2 = React.useMemo(() => {
        if (!color) return materials.material_5;
        const cloned = materials.material_5.clone();
        cloned.color.set(color);
        return cloned;
    }, [color, materials.material_5]);

    const hingeMaterial = React.useMemo(() => {
        if (!color) return materials.HINGE;
        const cloned = materials.HINGE.clone();
        cloned.color.set(color);
        return cloned;
    }, [color, materials.HINGE]);

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group position={[-0.032, -0.564, 5.873]} rotation={[Math.PI / 2, 0, 0]} scale={0.855}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder002_1.geometry}
                        material={headMaterial}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder002_2.geometry}
                        material={materials.EYES}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder002_3.geometry}
                        material={bodyMaterial}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder002_4.geometry}
                        material={hingeMaterial}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder002_5.geometry}
                        material={extraMaterial1}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder002_6.geometry}
                        material={extraMaterial2}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/scene.gltf')
export default Model;
